### ISSUE TITLE
Don’t keep this repo?

### ISSUE THREAD

**Issue by txuyuan** [AKEevee/hello-world#3]
Uh protip for keeping GitHub clean, remove any and all unused repos

**Comment by AKEevee** [comment]
yes we have a bug now

**Comment by txuyuan** [comment]
BUG REPORTTTTTTTTTT. FATAL BUGGGGGGGG. FIX PLSSSSSSSSSSSSSS AHHHHHHHHHHHH

(Don't judge math fried my brain)

**Comment by AKEevee** [comment]
math fired my brain too its fine 'we are all in this together, TOGETHER"

**Comment by txuyuan** [comment]
Ah yes my brain too was fired

**Comment by AKEevee** [comment]
yes my brian (pun on Grian) is on fire

**Comment by txuyuan** [comment]
FIRRRREEEEEEEEEEEE
AHHHHHHHHHHHHHHHHHHHHHH

**Comment by AKEevee** [comment]
ahhhhhhhhhhhhhhhhhhhhhhh

**Comment by txuyuan** [comment]
Bleh

**Comment by txuyuan** [comment]
你认为这个平台是好用的吗？

**Comment by AKEevee** [comment]
整体来说挺好用的！

**Comment by txuyuan** [comment]
你什么时间能学数据库的用法呢？

**Comment by AKEevee** [comment]
当我做完编采活动之后。
PS imagine chinese typos lol)
您钥匙掉了
您要死掉了

**Comment by txuyuan** [comment]
Nice.

**Comment by txuyuan** [comment]
Bleh how's ur progress on MongoDB we have like less than a month left

**Comment by AKEevee** [comment]
sorry I was very busy during the weekend that just ended cos of family stuff (aka being forced to play a certain game (that had an in-game event over the weekend) that i dont really like to I dont wanna talk too deep into it)
anyways its time to find a better C++ IDE first, any suggestions?

**Comment by txuyuan** [comment]
Ah ok. JetBrains CLion is good.

**Comment by txuyuan** [comment]
Jetbrains, Netbeans and Eclipse are known to make the best IDEs

**Comment by txuyuan** [comment]
Human target = Human.getHuman("Alrik");
Comment comment = new RandomComment(target);

**Comment by txuyuan** [comment]
target.setAlive(false);
target.setBodyBurned(true);

return "Success, mission complete";

**Comment by txuyuan** [comment]
public class Human extends Entity{

    private Boolean isAlive;
    private Boolean isBurned;
    
    public Human{
        
    }

    public void setAlive(Boolean alive){
        this.isAlive=alive
    }

    public void setBodyBurned(Boolean burned)}
        this.isBurned=burned
    }
}

**Comment by txuyuan** [comment]
Don't judge I'm in PE and there's nothing to do


 ![image](https://user-images.githubusercontent.com/72079021/127249384-4ee96c40-f9e7-47a4-82a1-3fd052bb6ed3.jpeg)

**Comment by sch231** [comment]
hbtsdk Hgsdtsfk jLig I suck

**Comment by AKEevee** [comment]
lovl

**Comment by AKEevee** [comment]
`for (int i=0; i<10: i++) pain=pain+i*i`

**Comment by txuyuan** [comment]
String pain;
  for(int i=0;i=<2000;i++)
    pain = pain + i*i*i*i
  System.out.println(pain)

**Comment by txuyuan** [comment]
if(project.getReport.getDueDate.getTime < 10)
    System.out.println("JINGDAAAAAAAAAAA");

**Comment by txuyuan** [comment]
![image](https://user-images.githubusercontent.com/72079021/128277400-2947479a-cdb6-4bd1-a343-6b06d8ef32a8.jpeg)

Again bored in PE

**Comment by txuyuan** [comment]
Babababababababababababababa

**Comment by txuyuan** [comment]
Imma continue spamming until you reply lol

**Comment by txuyuan** [comment]
Ahhhhhhhhhhhhhhhhhhh
![Poop](https://img.shields.io/badge/Poopa-734926?style=flat-square)

**Comment by txuyuan** [comment]
BlehBlehBlehBlehBlehBlehBlehBlehBlehBlehBleh

**Comment by txuyuan** [comment]
AHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH also i updated the notes and documentation for the TTA repos for no reason I was bored after oral dont judge ok bye
